[package]
name = "minecraft"
version = "0.1.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
serde_json = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.uuid]
version = "0.8"
features = ["serde"]
